name: AWS OIDC Connect Demo
on:
  push
env:
  AWS_REGION : "us-east-1"   
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  DemoOIDC:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::810082744037:role/github-actions
          role-session-name: samplerolesession
          aws-region: us-east-1
          
      - name: Print assumed role
        run: aws sts get-caller-identity
